<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.29" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FERNGSolver.Common.Application\FERNGSolver.Common.Application.csproj" />
    <ProjectReference Include="..\FERNGSolver.Common.UI.Blazor\FERNGSolver.Common.UI.Blazor.csproj" />
    <ProjectReference Include="..\FERNGSolver.Radiance.Application\FERNGSolver.Radiance.Application.csproj" />
    <ProjectReference Include="..\FERNGSolver.Radiance.Domain\FERNGSolver.Radiance.Domain.csproj" />
    <ProjectReference Include="..\FERNGSolver.Radiance.Presentation\FERNGSolver.Radiance.Presentation.csproj" />
  </ItemGroup>

</Project>
